server:
  port: 8081

spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      routes:
        - id: system-route
          uri: lb://system-service
          predicates:
            - Path=/api/**
          filters:
                # 去掉 /api 前缀，把 /api/crm/xxx 转为 /crm/xxx
                - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: admin-platform-secret-key-2024-admin-platform-secret-key-2024
  expiration: 604800000
